### ISSUE TITLE
Support for non Riemann Entities

### ISSUE THREAD

**Issue by wuast94** [Bl4DEx/HA_FixNegativeStatistics#1]
I think your script would fix my db too but i dont use Riemann Entities, would it be possibe to make it a "general" fix? 

I had a sensor that had communikation problems and was absent a few days. after it comes back HA was having the negative value issue.

in my case it seems that HA just added a "-" to the reading

![grafik](https://github.com/Bl4DEx/HA_FixNegativeStatistics/assets/16965460/5adb0180-ec75-416d-937b-e67163a7ea66)
![grafik](https://github.com/Bl4DEx/HA_FixNegativeStatistics/assets/16965460/94da368c-c8ad-4645-84ec-6cfdd9268e29)

**Comment by Bl4DEx** [comment]
Hello @wuast94 
I released v2.1.1 on sunday. It is no longer restricted to Riemann Sum entities. 
Can you execute on your database and give feedback?

**Comment by wuast94** [comment]
Will try it later and give feedback then :)

**Comment by wuast94** [comment]
```
sensor.strom_herd_import_active_energy | metadata_id_states = 478 | metadata_id_statistics = 123
  Fixing table statistics for key: sum
    Updating idx = 3841917: 0.0 -> 78.95
    Updating idx = 3842206: 0.0 -> 78.95
….
….
….
    Updating idx = 3891537: 0.0 -> 78.95
    Updating idx = 3891821: 0.0 -> 78.95
  Fixing table statistics for key: state
    Nothing was modified!
  Deleting short term statistics
    All entries deleted and replaced by a single entry with last valid value
  Fixing table states
  [ERROR]: Cannot fix this entity because first entry in table 'states' is not a number! first entry: 220
No changes were committed into the database!

```

**Comment by Bl4DEx** [comment]
Hi @wuast94 
this was a safety measurement. I updated the script to 2.2.0. Now, the script looks for the first valid value and starts from there

**Comment by wuast94** [comment]
as far as i can tell it worked, dont see any negative values anymore.

thx for youre awesome work dude 😊
